const mongoose = require('mongoose');
const validator = require('validator');

const listingSchema = new mongoose.Schema({
    title: {type: String, required: [true, 'Title is required']},
    description: {type: String, required: [true, 'Description is required']},
    price: {type: Number, required: [true, 'Price is required']},
    type: {type: String, required: [true, 'Type is required']},

    // id is generated by MongoDB
    // listingId: {type: Number, required: [true, 'ID is required'], unique: [true, 'ID is taken']},

    // convert the image into base64 encoded string, and store the string into the database
    image: {type: String, required: [false, 'Image is not required']}, // store image in db for now
    thumbnail: {type: String, required: [false, 'Thubmnail is not required']}, // store thumbnail in db for now
    
    // we need to store which user posted the listing
    userID: {type: String, required: [true, 'User ID is required']},
});

const Listing = mongoose.model('listings', listingSchema);

module.exports = Listing;